notifications:
  email: false
sudo: false
language: node_js
node_js:
  - "4"
  - "5"
before_script:
  - wget https://bitcoin.org/bin/bitcoin-core-0.11.2/bitcoin-0.11.2-linux64.tar.gz
  - tar -xf bitcoin-0.11.2-linux64.tar.gz
env:
  global:
    - PATH=./bitcoin-0.11.2/bin:$PATH
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=integration
matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=lint
script: npm run $TEST_SUITE
